FROM alpine:3.19 AS builder
WORKDIR /app

RUN apk add --no-cache nodejs npm

COPY package*.json ./
COPY ./src ./src
COPY ./prisma ./prisma
COPY ./tsconfig*.json ./

RUN npm ci
RUN npm run build

FROM alpine:3.19 AS final
WORKDIR /app

COPY --from=builder /app/dist ./dist
COPY ./package*.json ./
COPY ./prisma ./prisma

ARG DATABASE_URL
ARG BACKEND_PORT

ENV DATABASE_URL="postgresql://pguser:pgpass@localhost:5432/postgres?schema=public"
ENV BACKEND_PORT=3000

RUN apk add --no-cache nodejs npm
RUN npm ci --omit=dev



EXPOSE 3001
CMD ["npm", "start"]